apiVersion: v1
kind: ServiceAccount
metadata:
  name: cromwell-sa
  namespace: cromwell
--- 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cromwell-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "update", "get", "watch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cromwell-role
subjects:
  - kind: ServiceAccount
    name: cromwell-sa
    namespace: cromwell
roleRef:
  kind: ClusterRole
  name: cromwell-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cromwell
  namespace: cromwell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cromwell-server
  template:
    metadata:
      labels:
        app: cromwell-server
    spec:
      serviceAccount: cromwell-sa
      containers:
        - name: cromwell
          image: tyoshimura8869/cromwell-k8s:78
          workingDir: /tmp
          env:
            - name: JAVA_OPTS
              value: "-Dconfig.file=/cromwell.conf"
            - name: CROMWELL_ARGS
              value: "server"
          imagePullPolicy: "Always"
          volumeMounts:
            - name: cromwell-conf
              mountPath: /cromwell.conf
              readOnly: true
              subPath: cromwell.conf
            - name: cromwell-pvc
              mountPath: /cromwell_root
          ports:
            - containerPort: 80
      volumes:
        - name: cromwell-conf
          configMap:
            name: cromwell-cm
            items:
            - key: cromwell.conf
              path: cromwell.conf
        - name: cromwell-pvc
          persistentVolumeClaim:
            claimName: cromwell-pvc
